service: twitter-bot
useDotenv: true
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  tracing:
    lambda: true

functions:
  hello:
    handler: handler.twitBot
    events:
      - schedule: cron(45 1/7 ? * MON-FRI *)

    environment:
      TWITTER_CONSUMER_KEY: ${env:CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${env:CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN_KEY: ${env:ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
      TWITTER_BEARER_TOKEN: ${env:BEARER_TOKEN}
